######################################################################
#
# File name : pointdouble_tb_compile.do
# Created on: Tue Feb 11 20:40:23 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -work xil_defaultlib  \
"../../../../mod_count.srcs/sources_1/new/mod2_integer.v" \
"../../../../mod_count.srcs/sources_1/new/mod3_integer.v" \
"../../../../mod_count.srcs/sources_1/new/mod4_integer.v" \
"../../../../mod_count.srcs/sources_1/new/mod8_integer.v" \
"../../../../mod_count.srcs/sources_1/new/mod_add.v" \
"../../../../mod_count.srcs/sources_1/new/mod_reduce.v" \
"../../../../mod_count.srcs/sources_1/new/montgomery_mul.v" \
"../../../../mod_count.srcs/sources_1/new/mult256.v" \
"../../../../mod_count.srcs/sources_1/new/pointdouble2.v" \
"../../../../mod_count.srcs/sim_1/new/pointdouble_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

