# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath D:/Li/app1/modesim2019/win64
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xcku060-ffva1156-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Li/program/vivado_program/mod_test - 副本/mod_count.cache/wt} [current_project]
set_property parent.project_path {D:/Li/program/vivado_program/mod_test - 副本/mod_count.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Li/program/vivado_program/mod_test - 副本/mod_count.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/mod2_integer.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/mod3_integer.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/mod4_integer.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/mod8_integer.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/mod_add.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/mod_inv.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/mod_reduce.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/montgomery_mul.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/mult256.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/pointadd2.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/pointdouble2.v}
  {D:/Li/program/vivado_program/mod_test - 副本/mod_count.srcs/sources_1/new/k_point.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top k_point -part xcku060-ffva1156-3-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef k_point.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file k_point_utilization_synth.rpt -pb k_point_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
